import type { EncounterDef } from '../engine/types'

/**
 * Энкаунтеры акта 1. ASCII-доска: '.' пусто, '#' дыра, '*' расстановка игрока,
 * буквы — фигуры врага (p n b r q k), 'G' — ворота, d/v/s — особые фигуры.
 * shuffle: обе армии тасуются по своим клеткам сидом боя — каждый бой уникален.
 */
export const ENCOUNTERS: EncounterDef[] = [
  {
    id: 'a1-skirmish-pawns', name: 'Этюд с пешками',
    board: [
      '.n.k..n.',
      'pp.pp.pp',
      '........',
      '...##...',
      '........',
      '........',
      '********',
      '********',
    ],
    objective: { kind: 'regicide' },
    aiTier: 'apprentice',
    shuffle: true,
    gold: [18, 30],
  },
  {
    id: 'a1-bishops-study', name: 'Диагональный набросок',
    board: [
      '.b..k..b',
      'p.pp.pp.',
      '........',
      '.#....#.',
      '........',
      '........',
      '********',
      '********',
    ],
    objective: { kind: 'regicide' },
    aiTier: 'apprentice',
    shuffle: true,
    gold: [20, 32],
  },
  {
    id: 'a1-collage-drift', name: 'Съехавший коллаж',
    board: [
      '.n..k..n',
      'ppp..ppp',
      '........',
      '##....##',
      '........',
      '........',
      '********',
      '********',
    ],
    objective: { kind: 'regicide' },
    aiTier: 'journeyman',
    curatorPeriod: 3,
    shuffle: true,
    gold: [22, 36],
  },
  {
    id: 'a1-survive-flood', name: 'Красная волна',
    board: [
      'rnn..nnr',
      'pppppppp',
      '........',
      '........',
      '........',
      '........',
      '..****..',
      '.******.',
    ],
    objective: { kind: 'survive', turns: 8 },
    aiTier: 'journeyman',
    shuffle: true,
    gold: [26, 40],
  },
  {
    id: 'a1-escort-dawn', name: 'Гонец к рассвету',
    board: [
      '........',
      '.n....n.',
      '..b.pb..',
      '........',
      '#..##..#',
      '........',
      '.******.',
      '..****..',
    ],
    objective: { kind: 'escort', goalRow: 0 },
    aiTier: 'journeyman',
    shuffle: true,
    gold: [26, 40],
  },
  {
    id: 'a1-elite-frost', name: 'Элита: Хладный мазок',
    board: [
      '.bq..k.b',
      '.pp.s.pp',
      '...s....',
      '........',
      '.#....#.',
      '........',
      '********',
      '********',
    ],
    objective: { kind: 'regicide' },
    aiTier: 'master',
    enemyDeck: ['stiffen', 'stiffen', 'shove', 'palette'],
    enemyPaint: 4,
    shuffle: true,
    gold: [45, 60],
    elite: true,
  },
  {
    id: 'a1-boss-siege', name: 'ОСАДА ЗАМКА',
    board: [
      '..s..G..s',
      '.n..ss..n',
      'p.p....p.',
      '.........',
      '....##...',
      '.........',
      '.........',
      '*********',
      '*********',
    ],
    objective: { kind: 'siege' },
    aiTier: 'master',
    enemyDeck: ['freshStroke', 'freshStroke', 'stiffen', 'shove', 'palette'],
    enemyPaint: 5,
    curatorPeriod: 4,
    shuffle: true,
    gold: [70, 90],
    boss: true,
  },
]
